import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} h-full flex flex-col items-center w-full py-24`}
      >
        <h1>
          <Link href='/'>My Libraries</Link>
        </h1>
        <div className='w-full fledx justify-center py-10 px-24 grow'>
          {children}
        </div>
      </body>
    </html>
  );
}
