import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import SVGIMG from "../../public/assets/online-library.svg"
import Image from 'next/image';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} h-full flex flex-col items-center w-full py-24`}
      >
        <Link href={"/"} className='mb-4 rounded-full flex justify-center items-center'>
          <Image src={SVGIMG} alt="library icon" width={40} height={40} />
        </Link>
        <h1 className='mb-10'>
          <Link href='/'>My Libraries</Link>
        </h1>
        <div className='w-full flex justify-center grow px-10 pb-20'>
          {children}
        </div>
      </body>
    </html>
  );
}
